### ISSUE TITLE
Description for SCRIBBLE_HASH_NEWLINE causes parsing issues

### ISSUE THREAD

**Issue by glitchroy** [GameMakerDiscord/scribble#4]
The newline-character in the comment of the SCRIBBLE_NEW_HASHLINE macro (`__scribble_config()`, line 8) causes issues with parsing the next macro in line correctly.

Error log:  
```

___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Create Event
for object oInit:

Variable oInit.SCRIBBLE_COMPATIBILITY_MODE(100015, -2147483648) not set before reading it.
 at gml_Script_scribble_load_fonts (line 146) -         if ( SCRIBBLE_COMPATIBILITY_MODE ) global.__scribble_sprite_font_map[? _name ] = font_add_sprite_ext( _sprite, _sprite_string, true, _shift_constant );
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_scribble_load_fonts (line 146)
called from - gml_Script_scribble_init_end (line 13) - scribble_load_fonts( global.__scribble_init_font_array );
called from - gml_Object_oInit_Create_0 (line 6) - scribble_init_end();

```

As you can see, the next macro in line is not created correctly.

What doesn't work:  
Escaping the newline character, e.g. (`//Replaces hashes (#) with newlines (\\n) to emulate GMS1 behaviour`).  

What does work: Removing the `\n`.

Why a comment is parsed at all in this way is beyond me.  
Tested on scribble `v02.03.00`, GMS2 `v2.2.1.375`, GMS2 Runtime `v2.2.1.291`, Windows 10 1803.

**Comment by JujuAdams** [comment]
Thanks for flagging this up. Fixed in latest.
