### ISSUE TITLE
Mandatory "Fonts" folder in Included Files

### ISSUE THREAD

**Issue by glitchroy** [GameMakerDiscord/scribble#5]
With `scribble_init_start()`, a font directory needs to be specified, even if only sprite fonts are ever used. Furthermore, the directory has to contain at least one file.  
The given error (Line 22 in `scribble_init_start()`) outputs an unrelated and, at least on my system, not existing folder in AppData as the problem (using `game_save_id`).

I solved this error temporarily by adding a "Fonts" folder and a dummy file to my included files.  

Specs: `GMS2 v2.2.1.375, Runtime 2.2.1.287, Windows 10 1809`

**Comment by JujuAdams** [comment]
Probably an over-eager check for the directory's existece on by behalf; "...the directory has to contain at least one file" is likely GM not creating the directory when running the game if the directory contain no included files. Simple enough fix - shall address this later today with any luck.

**Comment by JujuAdams** [comment]
Fix was to change a forced error to a warning message instead. This warning message, combined with file existence checks in `scribble_init_end()`, will suffice to warn the developer if the directory is missing.

Fix is available in `dev` branch, or you can manually implement the two-line fix yourself: https://github.com/GameMakerDiscord/scribble/commit/807946ec81e3124d3cb4f4cc5b1c85589acec1d3
