### ISSUE TITLE
GM color constants in RGB instead of BGR

### ISSUE THREAD

**Issue by glitchroy** [GameMakerDiscord/scribble#8]
The native GMS colors are defined in the BGR format and thus, should set the optional `colourIsGameMakerBGR` in `scribble_add_colour()`.

https://github.com/GameMakerDiscord/scribble/blob/60151c89a756edc942b76a24869c88e91adffc40/scripts/scribble_init_start/scribble_init_start.gml#L63-L80

**Comment by JujuAdams** [comment]
Whooooops. Fixed in 4.5.1.
