### ISSUE TITLE
 Runtime 2.2.2.326+ breaks sprite fonts yet again

### ISSUE THREAD

**Issue by glitchroy** [GameMakerDiscord/scribble#9]
Looks like the newest runtime, `2.2.2.326` breaks sprite fonts again, like in #3.
Fortunately, it seems like it's only the padding around the font changed.
https://github.com/GameMakerDiscord/scribble/blob/60151c89a756edc942b76a24869c88e91adffc40/scripts/scribble_init_end/scribble_init_end.gml#L150-L151
Changing the `3` to a `1` in here seems to do the trick.  
It may have something to do with my texture group options (Border size: 2; Automatically crop on), but changing these does not seem to influence the generated cache files at all (at least not in a positive way - the automatic crop causes the letters to be tiny instead of too big).

I have `SCRIBBLE_EMULATE_LEGACY_SPRITEFONT_SPACING` turned off, too. Turning it on just causes the spacing between the letters to be 2 pixels too short.  

Running scribble `v4.4.1`, Windows 10 1809.

**Comment by JujuAdams** [comment]
Thanks for reporting this issue and suggesting a fix.

Why do YYG hate fonts? With YYG flipflopping on this I'm going to draw a line here and only support GMS2.2.2 runtimes for version 4.5.1 and later. It's too much of a pain to support all the various permutations and GMS2.2.2 is in stable now.
